server:
    port: 8111

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: @dbURL@
        username: @dbUserName@
        password: @dbPassWord@
        # Hikari 常用配置
        #数据源类型
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
            #自动提交从池中返回的连接
            auto-commit: true
            #连接池名称，默认HikariPool-1
            pool-name: HikariPool
            #最大连接数，小于等于0会被重置为默认值10；大于零小于1会被重置为minimum-idle的值
            maximum-pool-size: 20
            #连接超时时间:毫秒，小于250毫秒，否则被重置为默认值30秒
            connection-timeout: 30000
            #最小空闲连接，默认值10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
            minimum-idle: 10
            #空闲连接超时时间，默认值600000（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0；不等于0且小于10秒，会被重置为10秒。
            # 只有空闲连接数大于最大连接数且空闲时间超过该值，才会被释放
            idle-timeout: 600000
            #连接最大存活时间.不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短
            max-lifetime: 1800000
            #连接测试查询
            connection-test-query: select 1